### ISSUE TITLE
Issues with root view controller setter

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/Swiftilities#103]
https://github.com/Raizlabs/Swiftilities/blob/develop/Pod/Classes/RootViewController/UIWindow%2BRootViewController.swift

1. Doesn't call completion in non-animated case.
2. Doesn't dismiss the old root view controller before setting the new one, which can lead to the old root view controller being leaked. Here's how we fixed it in an app (Swift 2):

```swift
func showViewController(vc: UIViewController, animated: Bool) {
    guard let window = window else {
        preconditionFailure()
    }

    // If a view controller is currently presented, it must be dismissed before swapping the root VC of the window.
    // Failure to do this appears to result in a retain cycle in the orphaned VC stack.
    window.rootViewController?.dismissViewControllerAnimated(false, completion: nil)

    window.setRootViewController(vc, animated: animated)
    window.makeKeyAndVisible()
}
```

Thanks to @zadr for pointing these out.

**Comment by ZevEisenberg** [comment]
Question: how would this work in the animated case? If it dismisses the old VC immediately, it can't animate correctly, right? Maybe we grab a `UIViewController?` reference to the old VC, swap them, and then dismiss it afterwards? But that only works if we can dismiss a view controller that's no longer the root VC, and I don't know if you can do that. Maybe we just remove its view manually? @jvisenti?

**Comment by jvisenti** [comment]
@ZevEisenberg Not sure, worth testing. An option is to snapshot the VC `afterScreenUpdates: false` , do the dismissal, add the snapshot as a subview of the current root VC, set root VC animated, remove the snapshot.

**Comment by zadr** [comment]
If it helps, this is what I wound up doing. I haven't confirmed that the orphaned view controller is fully released, but I can confirm that it no longer shows up unexpectedly during transitions:

```
extension UIWindow {
    func transition(toRootViewController target: UIViewController, animated: Bool = true, completion: ((Bool) -> Void)? = nil) {
        guard rootViewController != nil else {
            rootViewController = viewController

            return
        }

        let previousRootViewController: UIViewController? = self.rootViewController
        let dismissPreviousRootViewController = {
            // If a view controller is currently presented, it must be dismissed before swapping the root VC of the window.
            // Failure to do this appears to result in a retain cycle in the orphaned VC stack.
            previousRootViewController?.dismiss(animated: false) { completed in
                previousRootViewController?.view.removeFromSuperview()
            }
        }

        guard animated else {
            self.rootViewController = viewController
            dismissPreviousRootViewController()
            completion?(true)

            return
        }

        UIView.transition(with: self, duration: 0.3, options: .transitionCrossDissolve, animations: {
            self.rootViewController = viewController
        }, completion: { (completed) in
            dismissPreviousRootViewController()
            completion?(completed)
        })
    }
}```

**Comment by ateliercw** [comment]
@zadr I'm adapting your code into Swiftilities, and it looks like your code misses calling completion if the root view controller is nil (which is unlikely, but still a case to make sure is covered). 👍 for the code overall though

**Comment by zadr** [comment]
oops yes, good catch on missing the `completion()` on the first `guard` as well, will fix on my end as well, thanks for the heads up 👍
